import type { Metadata } from "next";
import "./globals.css";
import { SuperContextProvider } from "@/Context/SuperContext";

export const metadata: Metadata = {
  title: "Portfolio | Nikhil",
  description: "Generated by Portfolio | Nikhil",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <SuperContextProvider>{children}</SuperContextProvider>
      </body>
    </html>
  );
}
